### PR TITLE
Add support for LoongArch64

### PR DESCRIPTION
**Pull request by heiher**
This PR adds support for [LoongArch64](https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html). (A Tier-2 target)

### CODE REVIEW

**Comment by kpcyrd** [comment]
Thanks for your contribution, I've pushed a fix for CI ([mips has been removed from Tier 2](https://github.com/rust-lang/compiler-team/issues/648) and tests started failing), tests should pass if you rebase your branch.

Please add `loongarch64-unknown-linux-gnu` to `.github/workflows/cross.yml` to ensure it keeps working correctly! :)

**Comment by heiher** [comment]
> Thanks for your contribution, I've pushed a fix for CI ([mips has been removed from Tier 2](https://github.com/rust-lang/compiler-team/issues/648) and tests started failing), tests should pass if you rebase your branch.
> 
> Please add `loongarch64-unknown-linux-gnu` to `.github/workflows/cross.yml` to ensure it keeps working correctly! :)

Thanks. all done.

**Comment by kpcyrd** [comment]
Thanks, I've released version 0.17.0 containing your change. :)

**Comment by heiher** [comment]
> Thanks, I've released version 0.17.0 containing your change. :)

Thank you. :heart:

**Pull request merged**
